### ISSUE TITLE
function blocks mutator breaking

### ISSUE THREAD

**Issue by falcarkiver** [Microsoft/pxt-blockly#215]
I'm working on the testing page and came across this weird behaviour by the mutator:
 
Behaviour:
![image](https://user-images.githubusercontent.com/32095835/54623030-9f37de80-4a62-11e9-971f-28c6d494d75b.png)

After dragging a block inside a mutator got this error.

Error:
![image](https://user-images.githubusercontent.com/32095835/54623085-c098ca80-4a62-11e9-9fdf-2ce4be267e27.png)

**Comment by gengshenghong** [comment]
Get the same issue today, blockly works with this to add parameters.

**Comment by pantoninho** [comment]
I've experienced the same issue too.

**Comment by abchatra** [comment]
We don’t support mutators anymore. Use blockly for mutators
