### ISSUE TITLE
nested get_variable block breaks a number of things in IE

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-blockly#84]
There's a bizarre issue with blocks that have get_variable blocks inside of them in IE. 
An example of this is the text_indexOf block in the playground. 
It's definition is: 
```
      <block type="text_indexOf">
        <value name="VALUE">
          <block type="variables_get">
            <field name="VAR">text</field>
          </block>
        </value>
        <value name="FIND">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
```

In IE, when this block is in the toolbox. A few things break, scrolling in the flyout no longer works, and when you drag, the filter applied on the block makes it hidden: 

![ievariablefields](https://user-images.githubusercontent.com/16690124/32565237-4d111b0e-c46b-11e7-8a5d-060e7c5121d2.gif)

Simply dragging out the get_variable block and re-connecting it fixes the issue of the disappearing block. 

Another workaround is to make the get_variable block a shadow block, although Blockly has an assert to avoid this (not sure why), but if we remove the assert scrolling and dragging work fine. 

Note: another block that suffers from similar behaviour. is the if / else block. Perhaps the same root cause.

@rachel-fenichel I'm pretty clueless as to what might be going on, any pointers?
I imagine this would repro in scratch-blocks, but I don't think scratch is using any nested get_variable blocks inside of the flyout.

**Comment by rachel-fenichel** [comment]
Is #83 a dupe of this?

This looks like a serious bug and I've got a couple of guesses, but I don't have a specific answer off the top of my head.

First off, I would expect it to repro in scratch-blocks, but also in Blockly on the playground.  Blockly and Scratch-blocks should be doing very similar things here.  Can you check if it happens in Blockly?

The if/else block doesn't have any variables, right?  Is it the same as the one on scratch-blocks?

If it were just variables I'd say we had a problem with the code that creates a variable as you drag in.  If it were just dragging blocks in IE I'd say the drag surface had a problem.  But not being able to scroll doesn't fit with either of those hypotheses.

Making get_variable a shadow block breaks in this case:
- drag out a block with a shadow variable block (creating the variable)
- cover the shadow
- delete the variable
- uncover the shadow

There's a forum thread about it that goes into more detail, but we're pretty convinced that the restriction is the right choice.

**Comment by microsoftsam** [comment]
Yes #83 was a dupe. Github is playing up on me today. 
Agreed, that it looks serious.

I can't get it to playground to load at all in IE locally, but this doesn't repro on the Blockly playground, not sure if that's out of date though. I'll try to get a repro.

The if/else block is custom, we have a custom mutation that's applied as we use the plus / minus buttons. but without any elseif and elses in the mutation, the bug doesn't repro. ie: the if block on it's own is fine, only when the mutation is applied (with elseifs or else) does it repro.

As for the side effects, the drag disappearing has something to do with the filter, as applying a filter: none to the block avoids the side effect, and the scrollbar has something to do with the height calculation, it returns a really low number for the getBBox in FlyoutVertical:getMetrics_.
I imagine the root cause has nothing to do with these side effects, but just trying to narrow it down a little.

Variable restriction makes sense.

**Comment by microsoftsam** [comment]
Confirmed repro in scratch-blocks. Easiest repro is to change any of the shadow blocks in default_toolbox to a data_variable. Breaks the flyout and drag.

**Comment by rachel-fenichel** [comment]
Which version of IE?

Blockly probably doesn't apply a filter on drag, and scratch-blocks probably does.  Still not sure about the if/else though.

**Comment by microsoftsam** [comment]
IE 11. Yeah Blockly is safe from the filter on drag issue but theoretically should still repro the flyout scrollbar issue.

**Comment by microsoftsam** [comment]
Issue is not reserved to having a block in the Flyout. If a variable block is inside of another block in the XML, the issue repro's when importing form XML also.
It's worth noting that the DOM does change when you disconnect and re-connect. I think the order of the blocks changes which might be affecting the filter that gets applied.

**Comment by microsoftsam** [comment]
So I've figured out what's causing this issue. but I have no idea what the right course of action is.

In both cases, the DOM generated has an extra blocklyPath element in it with a visibility:hidden. Removing that element fixes the issue. So does making it display:block. I presume it is visibility hidden for various bound calculations.

Changing this line of code to do a display:none instead fixes the issue: 
https://github.com/Microsoft/pxt-blockly/blob/develop/core/block_render_svg.js#L1309

but I doubt the fix is that easy!

My current thoughts are along the lines of, that element shouldn't be empty and the visibility hidden is only temporary, which means I should try and trace why that input is added but not used.
In the case of the if statement, I reckon I've just added an extra input somewhere.

**Comment by microsoftsam** [comment]
Okay!! I have a fix!

PR soon.

**Comment by microsoftsam** [comment]
Let me know your thoughts on https://github.com/Microsoft/pxt-blockly/pull/86

**Comment by microsoftsam** [comment]
Fixed.
