### ISSUE TITLE
exception in blockly.bindevent e.changedTouches is undefined

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-blockly#93]
Exception in touchWrapFunc (blockly.bindEvent_)
blockly_compressed.js:formatted:30094 Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLButtonElement.g (blockly_compressed.js:formatted:30094)

I think this might be related to my recent pointer event change.

**Comment by microsoftsam** [comment]
Possibly related to https://github.com/Microsoft/pxt-blockly/pull/92#issuecomment-348034226

**Comment by samelhusseini** [comment]
Fixed.
